version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      - "3000:8080" # http
    # env_file:
    #   - docker/web/.env
    depends_on:
      - db
    # Link to containers in another service
    links:
      - db
    volumes:
     - ../../../../.:/go

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: wyma
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myapp
    # volumes:
    #   /var/lib/mysql
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
