version: '2'
services:
    web:
      build: .
      depends_on:
        - db
      links:
        - db
      ports:
        - "3000:3000"
        
    db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: myapp
        MYSQL_USER: wyma
        MYSQL_PASSWORD: 1234
